export const esLang = {
    menu: ['Conoce', 'Ubicacion'],
    description: [
        'Cras accumsan ligula id nisi commodo, quis malesuada tellus fermentum. Vestibulum quam odio, tincidunt commodo placerat id, bibendum vitae nisl. In nisl sem, feugiat ac sodales ut, lobortis vel enim. Duis quis congue neque, ultrices ullamcorper elit. Cras bibendum, ipsum at aliquet sagittis, lectus risus rutrum felis, vel mollis enim magna sed nisi. Integer metus neque, facilisis vitae vehicula at, ornare nec mauris. Mauris quis neque sed sapien pharetra aliquet vel ac felis. Nulla quis ex in felis ultricies consectetur a sit amet risus. Sed nec ullamcorper orci. Aliquam erat volutpat. Sed fermentum dolor vel mi tristique eleifend. Sed sit amet tellus rutrum, ullamcorper urna ultrices, aliquet lectus. Phasellus vel lacinia lectus. Morbi ultricies dui sollicitudin tincidunt mollis. FIN DE TEXTO', 
    
        'Cras accumsan ligula id nisi commodo, quis malesuada tellus fermentum. Vestibulum quam odio, tincidunt commodo placerat id, bibendum vitae nisl. In nisl sem, feugiat ac sodales ut, lobortis vel enim. Duis quis congue neque, ultrices ullamcorper elit. Cras bibendum, ipsum at aliquet sagittis, lectus risus rutrum felis, vel mollis enim magna sed nisi. Integer metus neque, facilisis vitae vehicula at, ornare nec mauris. Mauris quis neque sed sapien pharetra aliquet vel ac felis. Nulla quis ex in felis ultricies consectetur a sit amet risus. Sed nec ullamcorper orci. Aliquam erat volutpat. Sed fermentum dolor vel mi tristique eleifend. Sed sit amet tellus rutrum, ullamcorper urna ultrices, aliquet lectus. Phasellus vel lacinia lectus. Morbi ultricies dui sollicitudin tincidunt mollis. FIN DE TEXTO'],
    contact: 'Asigna tu reserva ahora',
    designCopyRight: 'Diseñado por Gaiden',
    devCopyRight: 'Hecho por Rogelio'
}